FROM node:20-alpine

# Create app directory inside container
WORKDIR /app

# Copy only package files first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the backend code
COPY . .

ENV PORT=5000
# Expose Express port
EXPOSE 5000

# Start the server
CMD ["node", "server.js"]